added checks to add this to PATH

diff --git a/vm b/vm
--- a/vm
+++ b/vm
@@ -31,6 +31,18 @@ RED=$(tput setaf 1)
 GREEN=$(tput setaf 2)
 NC=$(tput sgr0)
 
+if [ ! -e "$(which vm 2>&1)" ]; then
+  echo "[+]script not in PATH, adding to PATH"
+  sudo cp $0 /usr/local/bin/vm
+  sleep 1
+  if [ -e "$(which vm 2>&1)" ]; then
+    echo -e "$GREEN[+] Successfully added to PATH$NC"
+  else
+    echo -e "$RED[+] Failed to add to PATH please try running again$NC"
+    exit 1
+  fi
+fi
+
 function vm_exist() {
   if_exists=$(virsh list --all | grep -w $1)
 
